### ISSUE TITLE
Outlook

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/SpreadSheetTool#71]
In the past term, we worked at a lot of basics for SqueakSheet. However, there are several open ideas for the project I would like to summarize here:

First, there are many open issues in this repo, just browse them. Also have a look at our [first vision thread](https://github.com/hpi-swa-teaching/SpreadSheetTool/issues/53) which is partially implemented at the moment.

I also have another vision for integrating SqueakSheet into a typical Squeak workflow: **Support many default sheets and configurations.** I want to sheet any object and be immediately displayed its composed information instead of needing to configure each cell manually.
- [ ] First, it is a pity that inspecting a simple matrix (or, as an edge case, a collection) is not yet possible using SqueakSheet on a convenient way. There should be some routine that automatically loads each formula with `self at: cell rowIndex at: cell columnIndex` & an equivalent putting setter, or something similar (#20)
- [ ] To make it really easy to sheet any object, an option could be introduced to provide
   * [ ] **default models per class:** For example, I would declare the SSBooleanHolder as default model for the Boolean class, or SSColorPicker as default model for the Color class.
     - depending on the current getter formula result, the UCM can pick the appropriate model
     - either store an extension method in each class (or even instance side? could allow an even higher dynamic 🤩), or just make a search in all known configurations (the latter lacks OOP-style, but strengthens cohesion. also you could define multiple relevant models per class)
     - open question: How to deal with changes? Should the displayed model possibly change in each step?
   * [ ] **default sheets per class:** An example is found in SSSheetTool class>>#exampleInspectingAMorph. It would be quite nice to support providing a default sheet for each possible class of subjects.
     - same question as above: store these default sheets in extension methods or just store a set of default sheets in our package?
     - What is about having many default sheets for one class? In general, most sheets using the inspection features of Squeak depend on a certain kind of subject. Maybe the current saving concept could be reconsidered respecting this point?
     - An advantage of extension methods would be the fact that they can do more than just return a default SSSheet(Tool) instance: An extension method could create the appropriate sheet for inspecting a matrix/collection as described above.
       Also, as a default sheet for Object, all instvars or accessors could be spread over the sheet's cells.

# Other open ideas
Kind of brainstorming. I tend to think unnecessarily abstract, but just some thoughts :)
## Table view
- [ ] Insert/delete rows/columns (as supported by Word/Excel)
- [ ] Keep relative size of rows/columns when changing their range
- [ ] Swap cells
- [ ] Advanced: Split/merge cells? This can be currently achieved by embedding a sheet into the sheet.
- [ ] **Range-based cell-operations,** for example enter a formula into each cell
- [ ] For some of the points above: Introduce something like a multi-selection mode?
- [ ] **Fixed header size:** As headers do not contain exchangeable models, it is not necessary to give them a large size when extending the window. Could be implemented using LayoutFrame offsets and another nested panel.
- [ ] **Improve saving UI:** Use UIManager's chooseFromOrAddTo... for saving a sheet (for overwriting an old sheet); allow multiselect when deleting sheets.
## Formulae
- [ ] **Setter formulae:** For example, let A1 have the getter `self color` and the setter `self color: value`; B1 have the getter `cell left darker`; and both use an appropriate color model. It would be great to enter a new color into B1 and have A1 be set to this color lighter. So ideally, the setter formula of B1 could be something like `cell left: value darker`. This would also require managing servers/clients inversed to our current approach for getter formulae.
- [ ] Range-based formulae (#46)
- [ ] Discussion: Should the cell formula API be transparent (#55)?
## UniversalCellModel
- [ ] **Accessor/instvar button (#67):** We already support complex formulae, but a common, much simpler desire might be to select any instvar or pair of accessors.
- [ ] **Cell title:** If I would like to find out the current instvar/accessor/formula for a cell, I always need to click a button. It would be nice to integrate this information somehow into the default UI of each UCM ([example](https://user-images.githubusercontent.com/38782922/59914434-acc28300-941a-11e9-970b-5c52b95beb88.png)). But don't overload the UI!
   * How to generate title for complex formulae? One option could be an ellipsis (…) or any kind of icon. Another idea would to analyze the formula and extract the relevant/unique part.
- [ ] **Increase delegation of control:** Formula managers like SSHybridFormulaHolder already exist. It would be possible to delegate further tasks to them, e. g. a BooleanHolder could request the title of the current cell and display it in its button/check box.
- [ ] There are several possible things that can be achieved using our ModelConfiguration:
   * [ ] Instead of just using selectors, custom contentGetter and contentSetter blocks could be specified, in order to avoid rewriting the same conversion ballast in each formula. On the other hand, this could be achieved using extension methods. Think about it ...
   * [ ] Just another wild idea: Could there be any benefit in supporting collection accessors in addition to regular accessors (contentGetter + contentSetter)? One example could be a model that encapsulates a PasteUpMorph and could be updated each time an observed collection, the submorphs of an inspected morph, changes.
   * [ ] Support custom step times per cell/model kind? Could be practical, but would require a redesign of the current stepping implementation.
- [ ] **Improve configuration dialogs:** Currently, we heavily use UIManager. For the model configuration, it would be nice to have an own configuration window that allows a non-linear control flow and choosing the relevant properties.
   It might also nice to have a graphical configuration manager for getting an overview about all active configurations.
- [ ] Support something like **Undo/Redo** for cell configuration/inputs? As we use arbitrary models, it could be very hard ...
- [ ] Idea: Support logging (as Compiler does, see SystemChangeNotifier)?
- [ ] @MrModder expressed the idea to support drag'n'drop for specifying subject-per-cells of the sheet. Discussion is needed to figure out how to join this concept with the current subject-per-sheet. Spike is needed to find out how to accept drops.

# Technical issues
- [ ] The test coverage without UI tests is rather bad. It would be good to write some unit tests, especially for UCM. Also, SWE will teach you that testing a foreign code is a good way to learn how it works :P
- [ ] It would be good to "reset" all configurations and saved sheets during test execution. @codeZeilen recommended to use DynamicVariables for that purpose.
- [ ] Investigation: How high would be the effort to support Squeak-5.0? We removed this dependency in those days without really thinking about it. Fastest way might be to have an image installed using SCI and fixing it manually.
- [ ] There are two workarounds for dealing with strange behavior of existing components: One in SSHybridTextMorph>>#refreshText, one in ProportionalSplitterMorph>>#mouseDown:. Just read the comments.
- [ ] We grabbed some methods from the image to install our SheetIt shortcuts (e. g. SmalltalkEditor class>>#initializeCmdKeyShortcuts or Morph>>#buildDebugMenu:). Obviously, this is not a good strategy. Find out how if there any better hooks or develop some in cooperation with the Inbox.
- [ ] Is there still any reason why we store SheetTools instead of Sheets in the image?
